services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:3000/api
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/logs:/app/logs
      - ./uploads:/app/uploads
    environment:
          - NODE_ENV=production
          - PORT=3000
          - MONGODB_URI=mongodb://admin:secret@mongo:27017/samla_db?authSource=admin  # Corregido
          - UPLOADS_DIR=/uploads
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=samla_db


volumes:
  mongo-data: